# Generated by Django 5.1 on 2024-12-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mymodel_created_at_alter_mymodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
