# Generated by Django 5.1 on 2024-12-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_myproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproduct',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
